spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 123
    driverClassName: org.h2.Driver

  liquibase:
    enabled: true

logging:
  level:
    com.smelov: debug

server:
  port: 8888
